-- Seed data: Plans, Entitlements, Quotas

-- Plans (map to Paddle price IDs via env vars)
INSERT INTO plans (key, family, tier, period, paddle_price_id) VALUES
  -- Chatbot only
  ('CHATBOT_STARTER_M', 'CHATBOT', 'STARTER', 'M', 'PRICE_CHATBOT_STARTER_M'),
  ('CHATBOT_STARTER_Y', 'CHATBOT', 'STARTER', 'Y', 'PRICE_CHATBOT_STARTER_Y'),
  ('CHATBOT_PRO_M', 'CHATBOT', 'PRO', 'M', 'PRICE_CHATBOT_PRO_M'),
  ('CHATBOT_PRO_Y', 'CHATBOT', 'PRO', 'Y', 'PRICE_CHATBOT_PRO_Y'),
  -- Voice only
  ('VOICE_STARTER_M', 'VOICE', 'STARTER', 'M', 'PRICE_VOICE_STARTER_M'),
  ('VOICE_STARTER_Y', 'VOICE', 'STARTER', 'Y', 'PRICE_VOICE_STARTER_Y'),
  ('VOICE_PRO_M', 'VOICE', 'PRO', 'M', 'PRICE_VOICE_PRO_M'),
  ('VOICE_PRO_Y', 'VOICE', 'PRO', 'Y', 'PRICE_VOICE_PRO_Y'),
  -- Bundle (Chatbot + Voice)
  ('BUNDLE_STARTER_M', 'BUNDLE', 'STARTER', 'M', 'PRICE_BUNDLE_STARTER_M'),
  ('BUNDLE_STARTER_Y', 'BUNDLE', 'STARTER', 'Y', 'PRICE_BUNDLE_STARTER_Y'),
  ('BUNDLE_PRO_M', 'BUNDLE', 'PRO', 'M', 'PRICE_BUNDLE_PRO_M'),
  ('BUNDLE_PRO_Y', 'BUNDLE', 'PRO', 'Y', 'PRICE_BUNDLE_PRO_Y')
ON CONFLICT DO NOTHING;

-- Entitlements (feature flags per plan)
INSERT INTO entitlements (plan_key, feature, value) VALUES
  -- CHATBOT_STARTER
  ('CHATBOT_STARTER_M', 'CHATBOT_ENABLED', 'true'),
  ('CHATBOT_STARTER_M', 'VOICE_ENABLED', 'false'),
  ('CHATBOT_STARTER_M', 'CUSTOM_BRANDING', 'false'),
  ('CHATBOT_STARTER_M', 'API_ACCESS', 'true'),
  ('CHATBOT_STARTER_Y', 'CHATBOT_ENABLED', 'true'),
  ('CHATBOT_STARTER_Y', 'VOICE_ENABLED', 'false'),
  ('CHATBOT_STARTER_Y', 'CUSTOM_BRANDING', 'false'),
  ('CHATBOT_STARTER_Y', 'API_ACCESS', 'true'),
  -- CHATBOT_PRO
  ('CHATBOT_PRO_M', 'CHATBOT_ENABLED', 'true'),
  ('CHATBOT_PRO_M', 'VOICE_ENABLED', 'false'),
  ('CHATBOT_PRO_M', 'CUSTOM_BRANDING', 'true'),
  ('CHATBOT_PRO_M', 'API_ACCESS', 'true'),
  ('CHATBOT_PRO_Y', 'CHATBOT_ENABLED', 'true'),
  ('CHATBOT_PRO_Y', 'VOICE_ENABLED', 'false'),
  ('CHATBOT_PRO_Y', 'CUSTOM_BRANDING', 'true'),
  ('CHATBOT_PRO_Y', 'API_ACCESS', 'true'),
  -- VOICE_STARTER
  ('VOICE_STARTER_M', 'VOICE_ENABLED', 'true'),
  ('VOICE_STARTER_M', 'CHATBOT_ENABLED', 'false'),
  ('VOICE_STARTER_M', 'CUSTOM_BRANDING', 'false'),
  ('VOICE_STARTER_M', 'API_ACCESS', 'true'),
  ('VOICE_STARTER_Y', 'VOICE_ENABLED', 'true'),
  ('VOICE_STARTER_Y', 'CHATBOT_ENABLED', 'false'),
  ('VOICE_STARTER_Y', 'CUSTOM_BRANDING', 'false'),
  ('VOICE_STARTER_Y', 'API_ACCESS', 'true'),
  -- VOICE_PRO
  ('VOICE_PRO_M', 'VOICE_ENABLED', 'true'),
  ('VOICE_PRO_M', 'CHATBOT_ENABLED', 'false'),
  ('VOICE_PRO_M', 'CUSTOM_BRANDING', 'true'),
  ('VOICE_PRO_M', 'API_ACCESS', 'true'),
  ('VOICE_PRO_Y', 'VOICE_ENABLED', 'true'),
  ('VOICE_PRO_Y', 'CHATBOT_ENABLED', 'false'),
  ('VOICE_PRO_Y', 'CUSTOM_BRANDING', 'true'),
  ('VOICE_PRO_Y', 'API_ACCESS', 'true'),
  -- BUNDLE_STARTER
  ('BUNDLE_STARTER_M', 'CHATBOT_ENABLED', 'true'),
  ('BUNDLE_STARTER_M', 'VOICE_ENABLED', 'true'),
  ('BUNDLE_STARTER_M', 'CUSTOM_BRANDING', 'true'),
  ('BUNDLE_STARTER_M', 'API_ACCESS', 'true'),
  ('BUNDLE_STARTER_Y', 'CHATBOT_ENABLED', 'true'),
  ('BUNDLE_STARTER_Y', 'VOICE_ENABLED', 'true'),
  ('BUNDLE_STARTER_Y', 'CUSTOM_BRANDING', 'true'),
  ('BUNDLE_STARTER_Y', 'API_ACCESS', 'true'),
  -- BUNDLE_PRO
  ('BUNDLE_PRO_M', 'CHATBOT_ENABLED', 'true'),
  ('BUNDLE_PRO_M', 'VOICE_ENABLED', 'true'),
  ('BUNDLE_PRO_M', 'CUSTOM_BRANDING', 'true'),
  ('BUNDLE_PRO_M', 'API_ACCESS', 'true'),
  ('BUNDLE_PRO_M', 'SSO_SAML', 'true'),
  ('BUNDLE_PRO_M', 'PRIORITY_SUPPORT', 'true'),
  ('BUNDLE_PRO_Y', 'CHATBOT_ENABLED', 'true'),
  ('BUNDLE_PRO_Y', 'VOICE_ENABLED', 'true'),
  ('BUNDLE_PRO_Y', 'CUSTOM_BRANDING', 'true'),
  ('BUNDLE_PRO_Y', 'API_ACCESS', 'true'),
  ('BUNDLE_PRO_Y', 'SSO_SAML', 'true'),
  ('BUNDLE_PRO_Y', 'PRIORITY_SUPPORT', 'true')
ON CONFLICT DO NOTHING;

-- Quotas (monthly limits)
INSERT INTO quotas (plan_key, metric, limit_int) VALUES
  -- CHATBOT_STARTER: 10k messages, 1M embed tokens, 1 seat
  ('CHATBOT_STARTER_M', 'CHAT_MESSAGES', 10000),
  ('CHATBOT_STARTER_M', 'EMBED_TOKENS', 1000000),
  ('CHATBOT_STARTER_M', 'SEATS', 1),
  ('CHATBOT_STARTER_Y', 'CHAT_MESSAGES', 10000),
  ('CHATBOT_STARTER_Y', 'EMBED_TOKENS', 1000000),
  ('CHATBOT_STARTER_Y', 'SEATS', 1),
  -- CHATBOT_PRO: 100k messages, 10M embed tokens, 5 seats
  ('CHATBOT_PRO_M', 'CHAT_MESSAGES', 100000),
  ('CHATBOT_PRO_M', 'EMBED_TOKENS', 10000000),
  ('CHATBOT_PRO_M', 'SEATS', 5),
  ('CHATBOT_PRO_Y', 'CHAT_MESSAGES', 100000),
  ('CHATBOT_PRO_Y', 'EMBED_TOKENS', 10000000),
  ('CHATBOT_PRO_Y', 'SEATS', 5),
  -- VOICE_STARTER: 300 minutes, 1 seat
  ('VOICE_STARTER_M', 'VOICE_MINUTES', 300),
  ('VOICE_STARTER_M', 'SEATS', 1),
  ('VOICE_STARTER_Y', 'VOICE_MINUTES', 300),
  ('VOICE_STARTER_Y', 'SEATS', 1),
  -- VOICE_PRO: 3000 minutes, 5 seats
  ('VOICE_PRO_M', 'VOICE_MINUTES', 3000),
  ('VOICE_PRO_M', 'SEATS', 5),
  ('VOICE_PRO_Y', 'VOICE_MINUTES', 3000),
  ('VOICE_PRO_Y', 'SEATS', 5),
  -- BUNDLE_STARTER: 20k messages, 600 minutes, 2M embed tokens, 3 seats
  ('BUNDLE_STARTER_M', 'CHAT_MESSAGES', 20000),
  ('BUNDLE_STARTER_M', 'VOICE_MINUTES', 600),
  ('BUNDLE_STARTER_M', 'EMBED_TOKENS', 2000000),
  ('BUNDLE_STARTER_M', 'SEATS', 3),
  ('BUNDLE_STARTER_Y', 'CHAT_MESSAGES', 20000),
  ('BUNDLE_STARTER_Y', 'VOICE_MINUTES', 600),
  ('BUNDLE_STARTER_Y', 'EMBED_TOKENS', 2000000),
  ('BUNDLE_STARTER_Y', 'SEATS', 3),
  -- BUNDLE_PRO: 200k messages, 6000 minutes, 20M embed tokens, 10 seats
  ('BUNDLE_PRO_M', 'CHAT_MESSAGES', 200000),
  ('BUNDLE_PRO_M', 'VOICE_MINUTES', 6000),
  ('BUNDLE_PRO_M', 'EMBED_TOKENS', 20000000),
  ('BUNDLE_PRO_M', 'SEATS', 10),
  ('BUNDLE_PRO_Y', 'CHAT_MESSAGES', 200000),
  ('BUNDLE_PRO_Y', 'VOICE_MINUTES', 6000),
  ('BUNDLE_PRO_Y', 'EMBED_TOKENS', 20000000),
  ('BUNDLE_PRO_Y', 'SEATS', 10)
ON CONFLICT DO NOTHING;
