export { 
  db,
  usersProfile,
  messagesLegacy as messages,
  emails,
  paddleCustomers,
  paddleProducts,
  paddlePrices,
  paddleInvoices,
  paddlePayments,
  trainingJobs,
  webhooksLog,
  webhookEventsLegacy as webhookEvents,
  subscriptionsLegacy as paddleSubscriptions,
  conversationsLegacy as conversations,
  voiceCallsLegacy as voiceCalls,
} from '@/lib/db';
