#!/bin/bash

# Unik AI Agent - Paddle Products & Prices Setup Script
# This script helps you set up products and prices in Paddle

echo "🚀 Paddle Setup Guide for Unik AI Agent"
echo "========================================="
echo ""
echo "This script will guide you through setting up Paddle products and prices."
echo ""
echo "⚠️  PREREQUISITES:"
echo "   1. Create a Paddle account at https://paddle.com"
echo "   2. Complete your seller profile"
echo "   3. Get your API credentials from Paddle Dashboard → Developer Tools → Authentication"
echo ""
echo "📋 YOU WILL NEED:"
echo "   - Vendor ID"
echo "   - Client ID (formerly Vendor Auth Code)"
echo "   - Client Secret"
echo "   - Webhook Secret (from Paddle Dashboard → Developer Tools → Notifications)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "PADDLE PRODUCT STRUCTURE FOR UNIK AI AGENT"
echo ""
echo "We need to create 3 products with 2 prices each (monthly & yearly):"
echo ""
echo "1️⃣  STARTER PLAN"
echo "   💰 Monthly: €19.99/month"
echo "   💰 Yearly:  €167.92/year (30% discount)"
echo "   ✨ Features: 500 conversations, Chatbot Widget & API, Knowledge Base"
echo ""
echo "2️⃣  PRO PLAN"
echo "   💰 Monthly: €29.99/month"
echo "   💰 Yearly:  €251.92/year (30% discount)"
echo "   ✨ Features: 1,500 conversations, Voice Agent, n8n Integration"
echo ""
echo "3️⃣  BUSINESS PLAN"
echo "   💰 Monthly: €39.99/month"
echo "   💰 Yearly:  €335.92/year (30% discount)"
echo "   ✨ Features: Unlimited conversations, Dedicated Support, Custom Integrations"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 STEP-BY-STEP INSTRUCTIONS:"
echo ""
echo "Since Paddle doesn't have a CLI tool like Stripe, follow these manual steps:"
echo ""
echo "STEP 1: Login to Paddle Dashboard"
echo "   → Go to https://vendors.paddle.com (or https://sandbox-vendors.paddle.com for testing)"
echo ""
echo "STEP 2: Create Products"
echo "   → Go to Catalog → Products"
echo "   → Click 'Add Product'"
echo "   → For each plan (Starter, Pro, Business):"
echo "     • Product Name: [Plan Name] - Unik AI Agent"
echo "     • Description: [Features listed above]"
echo "     • Tax Category: 'SaaS - Software as a Service'"
echo ""
echo "STEP 3: Create Prices"
echo "   → For each product, add 2 prices:"
echo "     • Monthly Price:"
echo "       - Billing Type: Subscription"
echo "       - Billing Period: Monthly"
echo "       - Amount: [see amounts above]"
echo "       - Currency: EUR"
echo "       - Trial Period: 7 days"
echo "     • Yearly Price:"
echo "       - Billing Type: Subscription"
echo "       - Billing Period: Yearly"
echo "       - Amount: [see amounts above]"
echo "       - Currency: EUR"
echo "       - Trial Period: 7 days"
echo ""
echo "STEP 4: Copy Price IDs"
echo "   → After creating each price, copy its Price ID (format: pri_xxxxx)"
echo "   → You'll need 6 price IDs total (3 monthly + 3 yearly)"
echo ""
echo "STEP 5: Set Up Webhook"
echo "   → Go to Developer Tools → Notifications"
echo "   → Add Notification Destination:"
echo "     • URL: https://your-domain.com/api/webhooks/paddle"
echo "     • Select all subscription events"
echo "     • Copy the Webhook Secret"
echo ""
echo "STEP 6: Update .env file"
echo "   → Add these variables to your .env file:"
echo ""
echo "   # Paddle Configuration"
echo "   PADDLE_ENV=sandbox  # or 'live' for production"
echo "   PADDLE_VENDOR_ID=your_vendor_id"
echo "   PADDLE_CLIENT_ID=your_client_id"
echo "   PADDLE_CLIENT_SECRET=your_client_secret"
echo "   PADDLE_WEBHOOK_SECRET=your_webhook_secret"
echo "   PADDLE_ENABLED=true"
echo ""
echo "   # Paddle Price IDs"
echo "   PADDLE_PRICE_STARTER=pri_starter_monthly_id"
echo "   PADDLE_PRICE_PRO=pri_pro_monthly_id"
echo "   PADDLE_PRICE_BUSINESS=pri_business_monthly_id"
echo ""
echo "STEP 7: Seed Database (Optional)"
echo "   → Run the database seed script to populate paddle_prices table:"
echo "   → npm run db:seed"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ TESTING YOUR SETUP:"
echo ""
echo "1. Use Paddle Sandbox environment first"
echo "2. Test checkout flow with test card: 4242 4242 4242 4242"
echo "3. Verify webhook events are received"
echo "4. Check subscription status in your dashboard"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 HELPFUL RESOURCES:"
echo ""
echo "   • Paddle API Docs: https://developer.paddle.com"
echo "   • Subscription Guide: https://developer.paddle.com/concepts/subscriptions"
echo "   • Webhook Reference: https://developer.paddle.com/webhooks/overview"
echo "   • Testing Guide: https://developer.paddle.com/concepts/payment-methods/test-cards"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 QUICK TIPS:"
echo ""
echo "   • Always test in Sandbox before going live"
echo "   • Paddle handles VAT/tax automatically for EU customers"
echo "   • You can offer coupons and discounts through Paddle Dashboard"
echo "   • Paddle provides hosted checkout - no PCI compliance needed"
echo "   • Customer portal is built-in for self-service cancellations"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎉 Once configured, your Paddle integration will be fully functional!"
echo ""
echo "For support, visit: https://paddle.com/support"
echo ""
